url: ''
baseurl: ''
title: 'Jekyllwind'

plugins:
  - jekyll-postcss

postcss:
  cache: false

core_api_url: https://core.acm.illinois.edu

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - node_modules
